stages:
  - stage: nuget_signing
    dependsOn: pack_net
    displayName: Sign Nuget
    jobs:
      - template: sign-artifacts/jobs/v2.yml@yaml-templates
        parameters:
          signType: Real
          teamName: $(TeamName)
          usePipelineArtifactTasks: false
          targetFolder: $(Build.ArtifactStagingDirectory)/nuget/signed
          signedArtifactName: nuget
          signedArtifactPath: signed
          displayName: Sign Phase
          condition: and(succeeded(), eq(variables.signingCondition, true))
      
      - template: nuget-msi-convert/job/v3.yml@yaml-templates
        parameters:
          yamlResourceName: yaml-templates
          artifactName: nuget
          artifactPatterns: |
            **/signed/*.nupkg
          artifactPath: signed
          propsArtifactName: nuget
          signType: Real
          postConvertSteps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: nuget
              downloadPath: $(Build.ArtifactStagingDirectory)\sign-verify
              patterns: |
                **/SignVerifyIgnore.txt

          - task: MicroBuildCodesignVerify@3
            displayName: verify signed msi content
            inputs:
              TargetFolders: |
                $(Build.ArtifactStagingDirectory)\bin\manifests
                $(Build.ArtifactStagingDirectory)\bin\manifests-multitarget
                $(Build.ArtifactStagingDirectory)\bin\msi-nupkgs
              ExcludeSNVerify: true
              ApprovalListPathForCerts: $(Build.ArtifactStagingDirectory)\sign-verify\SignVerifyIgnore.txt
